//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace RemotingAbonne.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchByISBNWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByAuhtorWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CommenterLivreWSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::RemotingAbonne.Properties.Settings.Default.RemotingAbonne_localhost_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchByISBNWSCompletedEventHandler SearchByISBNWSCompleted;
        
        /// <remarks/>
        public event SearchByAuhtorWSCompletedEventHandler SearchByAuhtorWSCompleted;
        
        /// <remarks/>
        public event CommenterLivreWSCompletedEventHandler CommenterLivreWSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchByISBNWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchByISBNWS(string isbn) {
            object[] results = this.Invoke("SearchByISBNWS", new object[] {
                        isbn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByISBNWSAsync(string isbn) {
            this.SearchByISBNWSAsync(isbn, null);
        }
        
        /// <remarks/>
        public void SearchByISBNWSAsync(string isbn, object userState) {
            if ((this.SearchByISBNWSOperationCompleted == null)) {
                this.SearchByISBNWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByISBNWSOperationCompleted);
            }
            this.InvokeAsync("SearchByISBNWS", new object[] {
                        isbn}, this.SearchByISBNWSOperationCompleted, userState);
        }
        
        private void OnSearchByISBNWSOperationCompleted(object arg) {
            if ((this.SearchByISBNWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByISBNWSCompleted(this, new SearchByISBNWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchByAuhtorWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchByAuhtorWS(string auteur) {
            object[] results = this.Invoke("SearchByAuhtorWS", new object[] {
                        auteur});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByAuhtorWSAsync(string auteur) {
            this.SearchByAuhtorWSAsync(auteur, null);
        }
        
        /// <remarks/>
        public void SearchByAuhtorWSAsync(string auteur, object userState) {
            if ((this.SearchByAuhtorWSOperationCompleted == null)) {
                this.SearchByAuhtorWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByAuhtorWSOperationCompleted);
            }
            this.InvokeAsync("SearchByAuhtorWS", new object[] {
                        auteur}, this.SearchByAuhtorWSOperationCompleted, userState);
        }
        
        private void OnSearchByAuhtorWSOperationCompleted(object arg) {
            if ((this.SearchByAuhtorWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByAuhtorWSCompleted(this, new SearchByAuhtorWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CommenterLivreWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CommenterLivreWS(string titre, string comment) {
            object[] results = this.Invoke("CommenterLivreWS", new object[] {
                        titre,
                        comment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CommenterLivreWSAsync(string titre, string comment) {
            this.CommenterLivreWSAsync(titre, comment, null);
        }
        
        /// <remarks/>
        public void CommenterLivreWSAsync(string titre, string comment, object userState) {
            if ((this.CommenterLivreWSOperationCompleted == null)) {
                this.CommenterLivreWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCommenterLivreWSOperationCompleted);
            }
            this.InvokeAsync("CommenterLivreWS", new object[] {
                        titre,
                        comment}, this.CommenterLivreWSOperationCompleted, userState);
        }
        
        private void OnCommenterLivreWSOperationCompleted(object arg) {
            if ((this.CommenterLivreWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CommenterLivreWSCompleted(this, new CommenterLivreWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchByISBNWSCompletedEventHandler(object sender, SearchByISBNWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByISBNWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByISBNWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchByAuhtorWSCompletedEventHandler(object sender, SearchByAuhtorWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByAuhtorWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByAuhtorWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CommenterLivreWSCompletedEventHandler(object sender, CommenterLivreWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CommenterLivreWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CommenterLivreWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591